### ISSUE TITLE
Not encode queryKey

### ISSUE THREAD

**Issue by noeliasfranco** [aupac/ember-aupac-typeahead#16]
Hi! I'm using the component and in the queryKey I need to pass something like this:

`queryKey='filter=company-name'`

The problem is that the component is encoding the = next to filter and because that the API is not returning the corresponding results. How can I do in order to not enconde the queryKey?

Thanks in advance!

**Comment by jackmatt2** [comment]
The URL encoding is part of the [typeahead.js](https://twitter.github.io/typeahead.js/) library so can't be changed.  Besides, I can't see how the above can possibly be a query parameter key anyway otherwise you would get a URL like this `/search?filter=company-name=YOUR-TEXT` . An `=` sign as part of a query key is not valid in any URL.  Do you mean `queryKey='filter'`?.  Then you would get a URL such as  `/search?filter=YOUR-TEXT`

**Comment by jackmatt2** [comment]
@noeliasfranco did you manage to get this working?
