### ISSUE TITLE
Adding ember-aupac-typeahead adds 80kb to my minified vendor.js file

### ISSUE THREAD

**Issue by acorncom** [aupac/ember-aupac-typeahead#4]
It looks like it's due to the use of the `ember-cli-htmlbars` dependency (https://github.com/aupac/ember-aupac-typeahead/blob/master/package.json#L58) and it's use in the component (https://github.com/aupac/ember-aupac-typeahead/blob/master/addon/components/aupac-typeahead.js#L204)

You've got the most feature complete typeahead add-on in the Ember ecosystem right now (I've just been doing some thorough research on it ;-), so I'd love to use yours.  But not sure I can justify the increase in payload size.  Any way that we might be able to change things around so the Handlebars system doesn't need to be loaded?

**Comment by jackmatt2** [comment]
@acorncom, I agree the payload is too big.

I am pretty sure it is due to the `ember-template-compiler` which is used for client side template compilation.  By default this is not included in a typical `ember build --environment=production`.

``` javascript
//index.js
if (config.includeTemplateCompiler) {
      app.import(app.bowerDirectory + '/ember/ember-template-compiler.js');
}
```

this allows the user to add their own custom templates.

``` javascript
//addon/components/aupac-typeahead.js
  compiledSuggestionTemplate : computed(function() {
    return Handlebars.compile(this.get('suggestionTemplate') || `<div class='typeahead-suggestion'>{{model}}</div>`);
  }),
```

I am not sure there is a way around this but definitely open to suggestions.

**Comment by acorncom** [comment]
@jackmatt2 A couple of ideas on making the payload smaller:
- change the defaults so that people like me don't get hurt if we don't read the entire readme ;-)  That'd be a breaking change, but would probably make you popular with all the folks who are including this info without realizing it.
- as far as adding custom templates, could you take advantage of the Ember component `templateForName` and `layout` properties somehow?  Based on the way they look, I think they might go away in the future, but they're still there in 2.0.1 ... https://github.com/emberjs/ember.js/blob/v2.0.1/packages/ember-views/lib/views/view.js#L765-L791  If you can, then it seems like you'd be able to allow folks to pass in alternate names that you could then read from their components folder without needing adjustments

I guess the question is: is the ability to tweak the `suggestionTemplate` an **expert mode** option or something you want to be offering to everyone?  If it isn't something that everyone needs, then I think it'd make sense to require folks to jump through a few more hoops prior to turning those additional features on.  Even subclassing your component might be an option ...

Thoughts?

**Comment by jackmatt2** [comment]
Yep, I like this idea.  So essentially instead of compiling a string the user will point to a `*.hbs` template and use that instead (which is already compiled by ember-cli).  I will need to investigate but essentially if the user could do.

`{{aupac-typeahead suggestionTemplate=myTemplate action=...}}`

and

`myTemplate` was a reference to a compiled `hbs` file on the controller, this would work perfectly and eliminate the need to client side compilation.

I am happy if this introduces a breaking change, I will just bump the major version.

**Comment by acorncom** [comment]
Yep, I like it to.  If they want the complexity, their template can look a bit messier ;-)

I'm out of the office the rest of the week, but am happy to help test things here when I get back if needed.

**Comment by jackmatt2** [comment]
@acorncom updated.  Can you try 2.0.0 and get back to me with the payload size now the `ember-template-compiler` has been removed?

**Comment by acorncom** [comment]
@jackmatt2 :+1: Using 2.0.2, the increase in payload size is now 9kb gzipped and minified.  Much better, thanks!
