### ISSUE TITLE
'action' function triggers twice: when selecting and when changing focus

### ISSUE THREAD

**Issue by 0x4e3** [aupac/ember-aupac-typeahead#42]
Hi!
I uses component like this:
```javascript
{{aupac-ember-data-typeahead placeholder="VIN" modelClass='vehicle' displayKey='vin' allowFreeInput=true queryKey='vin' minLength=5 action=(action 'getVehicle')}}
```
```getVehicle``` - is just an action with ```console.log(value)```
When I'm selecting item from a list of suggestions, I'm seeing ember model in the console, but when I'm pressing tab or clicking to another input I'm seeing another one output from the action — this time it's just a string. 

Can you help me to understand, what am I doing wrong?

**Comment by 0x4e3** [comment]
I found the reason — just remove ```allowFreeInput=true```, and every thing's fine.
But I need to be able to input a "free" value to create new vehicle model if there is no such on the backend. Is it possible?

**Comment by jackmatt2** [comment]
Yes, this is possible.  Use the regular `aupac-typeahead` and map all your vin numbers from the store as a list of strings instead of `ember-data models`.  Use the `action` function create the vehicle class manually.

`{{aupac-typehead allowFreeInput=true minLength=5 placeholder="VIN" source=vins selection=(readonly slectedVehicle.vin) action=(action 'createVehicle')}}`

**Comment by jackmatt2** [comment]
supplied workaround
