### ISSUE TITLE
Unit test components

### ISSUE THREAD

**Issue by jackmatt2** [aupac/ember-aupac-typeahead#8]
Add unit tests.

**Comment by frunjik** [comment]
Hi,

I am in the process of writing tests for the component.

The PR i made for changing the selector used in the test-helper, is not enough to make a test with, there are (still) several problems with the current test helper:

- The way the selector is used to find and select a suggestion is wrong.
The selector '.typeahead-suggestion:nth-child(x)', will only work if you give a 1 for the index argument, because every suggestion is added in its own (div) element. This means that each suggestion is the first child of its parent - ie the helper function will find (and click) all suggestions, when given a 1 for index - and it will fail to find suggestions given anything else then 1.

- The current helper function will not work if there is more then one type-ahead component on a page. (It will find all suggestions over all components.)

- I think the helper function(s) should be Async helper functions.

I have made a new version of test helpers (2 new functions) and i made tests with them in my own project.

Now i want to make a PR for including this but i want to include it with tests.

The thing is that the current empty test-suite gives me lots of deprecation errors / warnings that I would like to get rid of before I create and upload a PR.

Sadly my knowledge of Ember lacks for me to get rid of the warnings and deprecation's ...
(I tried).

Maybe we can join efforts on this ?

I don't know what the best way to progress is ...
